name: playfair
description: A simple charting library for Flutter
version: 0.0.9
author: Flutter Authors <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/playfair
dependencies:
  sky: any
  sky_tools: any
dev_dependencies:
  test: ^0.12.0
environment:
  sdk: '>=1.8.0 <2.0.0'
