name: playfair
description: A simple charting library for Sky
version: 0.0.6
author: Chromium Authors <sky-dev@googlegroups.com>
homepage: https://github.com/domokit/playfair
dependencies:
  sky: any
  sky_tools: any
dev_dependencies:
  test: ^0.12.0
environment:
  sdk: '>=1.8.0 <2.0.0'
